apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Buzzer
  labels:
    app: Buzzer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: Buzzer
    spec:
      containers:
      - name: Buzzer
        image: ITCS/Buzzer:1.0.0
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: Buzzer
  labels:
    app: Buzzer
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    app: Buzzer
  type: LoadBalancer
